name: Docker Image CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_USERNAME/dashbi:v1

    - name: Install Python and Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3
        pip install -r requirements.txt  # Reemplace requirements.txt con el nombre de su archivo de requerimientos
      shell: bash

    - name: Run Unit Tests
      run: pytest

    - name: Publish image to Docker Hub
      run: docker push $DOCKER_USERNAME/fraudetestapi
